CREATE TABLE "applicant" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"first_name" varchar NOT NULL,
	"last_name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"dob" varchar NOT NULL,
	"location" varchar NOT NULL,
	"device" varchar NOT NULL,
	"internet" varchar NOT NULL,
	"availability" varchar NOT NULL,
	"experience" varchar NOT NULL,
	"s3_url" varchar,
	"note" varchar NOT NULL,
	"status" varchar NOT NULL,
	CONSTRAINT "applicant_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "background_check" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"first_name" varchar NOT NULL,
	"last_name" varchar NOT NULL,
	"address" varchar NOT NULL,
	"email" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"dob" varchar NOT NULL,
	"ssn" varchar NOT NULL,
	"employer" varchar,
	"job_title" varchar,
	"ref_1_name" varchar,
	"ref_1_phone" varchar,
	"ref_1_email" varchar,
	"ref_2_name" varchar,
	"ref_2_phone" varchar,
	"ref_2_email" varchar,
	"criminal_record" varchar,
	"dl_front" varchar,
	"dl_back" varchar,
	"applicant_id" uuid,
	CONSTRAINT "background_check_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "idme" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"first_name" varchar NOT NULL,
	"last_name" varchar NOT NULL,
	"other_names" varchar NOT NULL,
	"address" varchar NOT NULL,
	"city" varchar NOT NULL,
	"state" varchar NOT NULL,
	"zip_code" varchar NOT NULL,
	"email" varchar NOT NULL,
	"phone" varchar NOT NULL,
	"dob" varchar NOT NULL,
	"ssn" varchar NOT NULL,
	"idme_username" varchar NOT NULL,
	"idme_password" varchar NOT NULL,
	"father_first" varchar NOT NULL,
	"father_last" varchar NOT NULL,
	"mother_first" varchar NOT NULL,
	"mother_last" varchar NOT NULL,
	"mothers_maiden" varchar NOT NULL,
	"state_of_birth" varchar NOT NULL,
	"city_of_birth" varchar NOT NULL,
	"dl_front" varchar,
	"dl_back" varchar,
	"w2_ssl" varchar,
	"applicant_id" uuid,
	CONSTRAINT "idme_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "background_check" ADD CONSTRAINT "background_check_applicant_id_applicant_id_fk" FOREIGN KEY ("applicant_id") REFERENCES "public"."applicant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idme" ADD CONSTRAINT "idme_applicant_id_applicant_id_fk" FOREIGN KEY ("applicant_id") REFERENCES "public"."applicant"("id") ON DELETE no action ON UPDATE no action;